In [73]:
import requests
import zipfile
import io
import os
import pandas as pd
import datetime
import time

def get_qualtrics_survey_data(dir_save_survey, survey_id):# dir_save_survey is the directory to which these exported files are to be saved.
   
    # Setting user Parameters
    api_token = "nEOlIxeWbcgAkcAbtk9uD8ZyT0YnCQV9AIIRQCcL"
    file_format = "csv"
    data_center = 'amazoneu.syd1' # "<Organization ID>.<Datacenter ID>"
    # Setting static parameters
    request_check_progress = 0
    progress_status = "in progress"
    base_url = "https://{0}.qualtrics.com/API/v3/responseexports/".format(data_center)
    headers = {
        "content-type": "application/json",
        "x-api-token": api_token,
    }
    # Step 1: Creating Data Export
    download_request_url = base_url
    download_request_payload = '{"format":"csv","useLabels": true ,"surveyId":"' + survey_id + '"}' # you can set useLabels:True to get responses in text format
    download_request_response = requests.request("POST", download_request_url, data=download_request_payload, headers=headers)
    progress_id = download_request_response.json()["result"]["id"]
    # print(download_request_response.text)
    # Step 2: Checking on Data Export Progress and waiting until export is ready
    while request_check_progress < 100 and progress_status != "complete":
        request_check_url = base_url + progress_id
        request_check_response = requests.request("GET", request_check_url, headers=headers)
        request_check_progress = request_check_response.json()["result"]["percentComplete"]
    # Step 3: Downloading file
    request_download_url = base_url + progress_id + '/file'
    request_download = requests.request("GET", request_download_url, headers=headers, stream=True)
    # Step 4: Unzipping the file
    zipfile.ZipFile(io.BytesIO(request_download.content)).extractall(dir_save_survey)
    print('Downloaded qualtrics survey')
path = "C:\\Users\\komatiyk\\Downloads\\Qualtrics Weekly Files"

# definining the suvery ID's with Specalist Names
Gurramr = "SV_0Ai7eAuueB6M6gJ"
ddlc = "SV_26alR8n753kAbyu"
dhahiman = "SV_8qdBdGLpsZRHAjA"
Fbhagat = "SV_9mn7lVJCPPAXNTn"
keziaidi = "SV_afMqjeuQ0UOg1qS"
khandh = "SV_8AmcjQKwidXNGG9"
komatiyk = "SV_eRHKjxVDveyIPoG"
mohlipsa = "SV_8w5mrVpJpX5RB6m"
parniv = "SV_6JqeQjoUW0D6RmK"
pratvel = "SV_9nSSDCPpLdaykf4"
Premalatha = "SV_29mXA0vS5qh5HqC"
prkujh= "SV_4HoXXHRb9ptxWbc"
prsrivas= "SV_42bdrRgDB7KUAiW"
rajchat= "SV_7ai49aIbpdjClnw"
tatii = "SV_efHw2haEtbUs7yK"
tgganesa = "SV_5bh19yBpdd1MF3o"
list = [ddlc, dhahiman, Fbhagat, keziaidi, komatiyk, mohlipsa, parniv, pratvel, Premalatha, prkujh, prsrivas, rajchat,tatii,tgganesa]
[get_qualtrics_survey_data(dir_save_survey = path, survey_id = i) for i in list]

Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [74]:
ddlc = pd.read_csv("Technical Onboarding CSAT- 2022(ddlc).csv")
dhahiman = pd.read_csv("Technical Onboarding CSAT- 2022(dhahiman).csv")
Fbhagat = pd.read_csv("Technical Onboarding CSAT- 2022(Fbhagat).csv")
keziaidi = pd.read_csv("Technical Onboarding CSAT- 2022(keziaidi).csv")
komatiyk = pd.read_csv("Technical Onboarding CSAT- 2022(komatiyk).csv")
mohlipsa = pd.read_csv("Technical Onboarding CSAT- 2022(mohlipsa).csv")
parniv = pd.read_csv("Technical Onboarding CSAT- 2022(parniv).csv")
pratvel = pd.read_csv("Technical Onboarding CSAT- 2022(pratvel).csv")
Premalatha = pd.read_csv("Technical Onboarding CSAT- 2022(Premalatha).csv")
prkujh = pd.read_csv("Technical Onboarding CSAT- 2022(prkujh).csv")
rajchat = pd.read_csv("Technical Onboarding CSAT- 2022(rajchat).csv")
tgganesa = pd.read_csv("Technical Onboarding CSAT- 2022(tgganesa).csv")
tatii = pd.read_csv("Technical Onboarding CSAT- 2022(tatii).csv")

#List1 = (
#     Fbhagat = pd.read_csv("Technical Onboarding CSAT- 2022(Fbhagat).csv"),Premalatha = pd.read_csv("Technical Onboarding CSAT- 2022(Premalatha).csv"),ddlc = pd.read_csv("Technical Onboarding CSAT- 2022(ddlc).csv"),dhahiman = pd.read_csv("Technical Onboarding CSAT- 2022(dhahiman).csv"),keziaidi = pd.read_csv("Technical Onboarding CSAT- 2022(keziaidi).csv"),komatiyk = pd.read_csv("Technical Onboarding CSAT- 2022(komatiyk).csv"),mohlipsa = pd.read_csv("Technical Onboarding CSAT- 2022(mohlipsa).csv"),parniv = pd.read_csv("Technical Onboarding CSAT- 2022(parniv).csv"),pratvel = pd.read_csv("Technical Onboarding CSAT- 2022(pratvel).csv"),prkujh = pd.read_csv("Technical Onboarding CSAT- 2022(prkujh).csv"),
#     rajchat = pd.read_csv("Technical Onboarding CSAT- 2022(rajchat).csv"),tatii = pd.read_csv("Technical Onboarding CSAT- 2022(tatii).csv"),tgganesa = pd.read_csv("Technical Onboarding CSAT- 2022(tgganesa).csv")
# )

In [75]:
# # Names defined as in Astro Report: 'Harish Ganesan', 'Lakshmi Pratyusha Velamakanni', 'Farah Bhagat',
#        'Niveditha Parvatha', 'PRAKASH JHA', 'Premalatha maddirala',
#        'Himanshu Dhami', 'Yashwant Komati', 'Dilip Chavali',
#        'Indra Tatikonda', 'Rajarshi Chatterjee', 'Lipsa Mohanty',
#        'KEZIA IDIKKULA MUTHALALY'

## By doing the below we are adding a column SPOC with the Specalist's name against the feedback received and removing the extra header rows on individual file.

ddlc['SPOC'] = "DILIP CHAVALI"
ddlc.drop([0,1],inplace= True)
Fbhagat['SPOC'] = "FARAH BHAGAT"
Fbhagat.drop([0,1],inplace= True)
dhahiman['SPOC'] = "HIMANSHU DHAMI"
dhahiman.drop([0,1],inplace= True)
keziaidi['SPOC'] = "KEZIA IDIKKULA MUTHALALY"
keziaidi.drop([0,1],inplace= True)
komatiyk['SPOC'] = "YASHWANT KOMATI"
komatiyk.drop([0,1],inplace= True)
mohlipsa['SPOC'] = "LIPSA MOHANTY"
mohlipsa.drop([0,1],inplace= True)
parniv['SPOC'] = "NIVEDITHA PARVATHA"
parniv.drop([0,1],inplace= True)
pratvel['SPOC'] = "LAKSHMI PRATYUSHA VELAMAKANNI"
pratvel.drop([0,1],inplace= True)
Premalatha['SPOC'] = "PREMALATHA MADDIRALA"
Premalatha.drop([0,1],inplace= True)
prkujh['SPOC'] = "PRAKASH JHA"
prkujh.drop([0,1],inplace= True)
rajchat['SPOC'] = "RAJARSHI CHATTERJEE"
rajchat.drop([0,1],inplace= True)
tgganesa['SPOC'] = "HARISH GANESAN"
tgganesa.drop([0,1],inplace= True)
tatii['SPOC'] = "INDRA TATIKONDA"
tatii.drop([0,1],inplace= True)

In [76]:
df_merged = pd.concat([ddlc,dhahiman, Fbhagat, keziaidi, komatiyk, mohlipsa, parniv, pratvel, Premalatha, prkujh, rajchat, tgganesa, tatii])

df_merged # All Feedbacks

,ResponseID,ResponseSet,IPAddress,StartDate,EndDate,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,...,Q2_1,Q3,Q4,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC,Score-sum,Score-weightedAvg,Score-weightedStdDev
2,R_3maDsWCzZBHBNUu,NaN,91.241.18.19,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,...,3 -Fair,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI,NaN,NaN,NaN
3,R_C36gknwR1sf3SPD,NaN,3.88.93.236,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,...,5- Excellent,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI,NaN,NaN,NaN
4,R_2YldibFOkrIilqh,NaN,52.95.75.9,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,...,5- Excellent,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI,NaN,NaN,NaN
5,R_3jd1JKYRO0XKwUF,NaN,93.56.31.152,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,...,5- Excellent,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI,NaN,NaN,NaN
6,R_1EhQUTTXRKWcd2S,NaN,87.200.21.74,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,...,4- Good,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,R_1DIr2SUuQmDmDSZ,NaN,78.134.72.11,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,...,5- Excellent,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA,NaN,NaN,NaN
46,R_1jdgmhL8zo6tYpL,NaN,51.155.23.77,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,...,5- Excellent,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA,NaN,NaN,NaN
47,R_PXwToEDr3GX9xU5,NaN,54.239.6.185,2023-06-15 10:56:12,2023-06-15 10:56:59,NaN,NaN,NaN,NaN,1,...,4- Good,d,NaN,50.1188,8.6843,-1,INDRA TATIKONDA,NaN,NaN,NaN
48,R_1EbaMaD93pgY6Td,NaN,54.239.6.184,2023-06-26 13:33:29,2023-06-26 13:40:48,NaN,NaN,NaN,NaN,1,...,5- Excellent,AJKTJJ9LD2M9I,Perfect support. Was making time to jump in a meeting on short notice. Helped to resolve an issue that was impacting all clients orders.,50.1188,8.6843,-1,INDRA TATIKONDA,NaN,NaN,NaN
49,R_6MAhGZ5EWELerW9,NaN,94.89.28.10,2023-06-27 08:59:52,2023-06-27 09:00:31,NaN,NaN,NaN,NaN,1,...,5- Excellent,A3CCGCDRNSK3MY,NaN,43.7891,11.2356,-1,INDRA TATIKONDA,NaN,NaN,NaN

In [77]:
#Dropping unneccesary columns and renaming certain columns for easy reference.

merged_mod = df_merged.drop(columns=['ResponseID','ResponseSet','IPAddress','Score-sum','Score-weightedAvg','Score-weightedStdDev'])

merged_mod.rename(columns={'StartDate': 'Start_Date', 'EndDate': 'End_date','RecipientLastName': 'Specalist_Name', 'Q1': 'Rating of the overall Support','Q2_1': 'Knowledge of SP-API products & Services','Q2_2': 'Ability to communicate clearly','Q3': 'Merchant_Token', 'Q4': 'Comments'}, inplace=True)

merged_mod[['Start_Date','End_date']]= merged_mod[['Start_Date','End_date']].apply(pd.to_datetime)

merged_mod['Merchant_Token'].fillna('0')

merged_mod

,Start_Date,End_date,Specalist_Name,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,Status,Rating of the overall Support,Ability to communicate clearly,Knowledge of SP-API products & Services,Merchant_Token,Comments,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC
2,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,3 -Fair,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI
3,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI
4,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI
5,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,5- Excellent,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI
6,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,4- Good,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA
46,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA
47,2023-06-15 10:56:12,2023-06-15 10:56:59,NaN,NaN,NaN,NaN,1,0,4- Good,4- Good,4- Good,d,NaN,50.1188,8.6843,-1,INDRA TATIKONDA
48,2023-06-26 13:33:29,2023-06-26 13:40:48,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,AJKTJJ9LD2M9I,Perfect support. Was making time to jump in a meeting on short notice. Helped to resolve an issue that was impacting all clients orders.,50.1188,8.6843,-1,INDRA TATIKONDA
49,2023-06-27 08:59:52,2023-06-27 09:00:31,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A3CCGCDRNSK3MY,NaN,43.7891,11.2356,-1,INDRA TATIKONDA

In [78]:
# Creating a column "Key" which is a combination of Merchant Token + the Speclalist's name, which would help us compare the feedbacks with cases on Astro

merged_mod['Key'] = merged_mod.Merchant_Token.str.cat(merged_mod.SPOC)

merged_mod['Ability to communicate clearly'] = merged_mod['Ability to communicate clearly'].astype(str).str.split('-').str[0].astype(int)
merged_mod['Knowledge of SP-API products & Services'] = merged_mod['Knowledge of SP-API products & Services'].astype(str).str.split('-').str[0].astype(int)

merged_mod['Average CSAT'] = (merged_mod['Ability to communicate clearly'] + merged_mod['Knowledge of SP-API products & Services']) / 2

merged_mod

,Start_Date,End_date,Specalist_Name,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,Status,Rating of the overall Support,Ability to communicate clearly,Knowledge of SP-API products & Services,Merchant_Token,Comments,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC,Key,Average CSAT
2,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,0,4- Good,5,3,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI,A11OKMLEOWRUTYDILIP CHAVALI,4.0
3,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI,A1Y1NMNJFO9AZHDILIP CHAVALI,5.0
4,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI,A2WJJHFR3EZX13DILIP CHAVALI,5.0
5,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,0,4- Good,5,5,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI,A39JLZTLGJEAS9DILIP CHAVALI,5.0
6,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,0,4- Good,5,4,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI,lenish@dynamicsstream.comDILIP CHAVALI,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA,A29BCDAL77UPK2INDRA TATIKONDA,5.0
46,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA,A1023IQIDP1IRBINDRA TATIKONDA,5.0
47,2023-06-15 10:56:12,2023-06-15 10:56:59,NaN,NaN,NaN,NaN,1,0,4- Good,4,4,d,NaN,50.1188,8.6843,-1,INDRA TATIKONDA,dINDRA TATIKONDA,4.0
48,2023-06-26 13:33:29,2023-06-26 13:40:48,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,AJKTJJ9LD2M9I,Perfect support. Was making time to jump in a meeting on short notice. Helped to resolve an issue that was impacting all clients orders.,50.1188,8.6843,-1,INDRA TATIKONDA,AJKTJJ9LD2M9IINDRA TATIKONDA,5.0
49,2023-06-27 08:59:52,2023-06-27 09:00:31,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A3CCGCDRNSK3MY,NaN,43.7891,11.2356,-1,INDRA TATIKONDA,A3CCGCDRNSK3MYINDRA TATIKONDA,5.0

In [81]:
merged_mod.to_csv('Merged_FB_File.csv') # Converting the aggregated feedbacks to a CSV file

In [82]:
astro = pd.read_csv('DataAstro.csv') # Importing astro report without paid
astro = astro.rename(columns={'key': 'Key'})
astro[['create_date','listing_complete_date', 'integration_start_date','handoff_date']]= astro[['create_date','listing_complete_date', 'integration_start_date','handoff_date']].apply(pd.to_datetime)
astro

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,6/12/2023,1106256,4.789394e+10,A3GQ5ONWIQ9PID,A3GQ5ONWIQ9PIDIndra Tatikonda,FindTape (Japan),JP,Technical Onboarding Request - New Seller,Completed,2021-07-21,2021-09-01,Indra Tatikonda,2021-08-17,DSR - Migration,2021-08-02
1,6/12/2023,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPremalatha Maddirala,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,Premalatha Maddirala,2023-04-20,MIGRATION_AB,2023-04-20
2,6/12/2023,1567266,5.100887e+08,A32URRHD2J995G,A32URRHD2J995GPremalatha Maddirala,ReinigungsBerater,DE,Push Back,Cancelled,2023-05-04,NaT,Premalatha Maddirala,NaT,DSR,2023-05-08
3,6/12/2023,1098047,1.471784e+10,A3HOPLRF61I8Z5,A3HOPLRF61I8Z5Dilip Chavali,Yuca LTD UK,UK,Technical Onboarding Request - New Seller,Completed,2021-06-08,2021-11-26,Dilip Chavali,2021-05-12,3PD_INTEGRATOR,2021-05-12
4,6/12/2023,1573435,4.614223e+07,A2PVIXJF9UTT7R,A2PVIXJF9UTT7RRajarshi Chatterjee,GourmetGiftBaskets.com,US,Technical Onboarding Request - New Seller,WIP,2023-05-18,NaT,Rajarshi Chatterjee,2023-05-18,migration_1P,2023-05-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231,6/12/2023,1394064,1.859954e+10,A2HCFN68KH3Q5J,A2HCFN68KH3Q5JFarah Bhagat,Pera Limonera Lifestyle,ES,Technical Onboarding Request - Reintegration,WIP,2023-01-17,NaT,Farah Bhagat,2023-01-20,DSR-SP_API INTEGRATION,2023-01-20
1232,6/12/2023,1321856,7.244474e+10,A2GIWHDB2WEDIG,A2GIWHDB2WEDIGRajarshi Chatterjee,GoedGepickt,UK,Technical Onboarding Request - New Seller,Cancelled,2022-05-20,NaT,Rajarshi Chatterjee,2022-05-30,DSR,2022-05-20
1233,6/12/2023,1354558,2.856930e+11,A3SPBNBRY5GT11,A3SPBNBRY5GT11Yashwant Komati,متجر أسراركو للتسوق asrar-co,SA,Technical Onboarding Request - New Seller,Cancelled,2022-09-12,NaT,Yashwant Komati,NaT,NaN,2022-09-13
1234,6/12/2023,1080474,1.670540e+11,A3VS3C5O1Q39VF,A3VS3C5O1Q39VFDilip Chavali,Luca Vanucci Firenze,UK,Push Back,Cancelled,2021-03-16,NaT,Dilip Chavali,NaT,NaN,2021-03-31
1235,6/12/2023,1356607,7.913905e+09,A2AAP1ZNM6SPO6,A2AAP1ZNM6SPO6Yashwant Komati,Eiz Pty Ltd,AU,Technical Onboarding Request - New Seller,Completed,2022-09-19,2022-08-31,Yashwant Komati,2022-07-25,DSR_INTEGRATOR_AES,2022-07-15

In [83]:
astro_paid = pd.read_excel('Astro_Paid.xlsx', sheet_name='Paid')
astro_paid = astro_paid.rename(columns={'key': 'Key'})
astro_paid[['create_date','listing_complete_date', 'integration_start_date','handoff_date']]= astro_paid[['create_date','listing_complete_date', 'integration_start_date','handoff_date']].apply(pd.to_datetime)
astro_paid

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,2023-06-12,163175,1211291772,AUNGYH863E97M,AUNGYH863E97MDilip Chavali,vidaXL IT,EU,Technical Onboarding Request - New Seller,Completed,2022-05-11 00:00:00,2023-04-24 16:22:00,Dilip Chavali,2022-05-11 20:51:00,PAID,NaT
1,2023-06-12,182768,47590974012,A3Q145GG5GOJFD,A3Q145GG5GOJFDNiveditha Parvatha,Joyería TOUS,EU,Technical Onboarding Request - New Seller,Completed,2022-06-14 00:00:00,2023-03-10 00:00:00,Niveditha Parvatha,2022-06-14 02:34:00,PAID,NaT
2,2023-06-12,220004,757310623,A175O6N7UW1356,A175O6N7UW1356PRAKASH JHA,S&O Handelsgesellschaft mbH,EU,Technical Onboarding Request - Reintegration,WIP,2022-08-08 00:00:00,NaT,PRAKASH JHA,2022-08-08 15:45:00,Paid,NaT
3,2023-06-12,247216,7647118235,A27DL0OMONAIX2,A27DL0OMONAIX2Yashwant Komati,Juvenilis,EU,Technical Onboarding Request - Reintegration,Completed,2022-09-13 20:48:00,2023-04-24 16:33:00,Yashwant Komati,2022-09-13 20:48:00,PAID,NaT
4,2023-06-12,261671,14816121112,A3I7IG61W9TCJR,A3I7IG61W9TCJRLipsa Mohanty,LULUBUY S.A.R.L,EU,Technical Onboarding Request - Reintegration,Completed,2022-09-29 21:44:00,2023-04-12 01:13:00,Lipsa Mohanty,2022-09-29 21:44:00,PAID,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,2023-06-12,493052,78178837412,A16KNVL00HJUQF,A16KNVL00HJUQFPremalatha Maddirala,Tudetic,EU,Technical Onboarding Request - New Seller,WIP,2023-05-22 15:21:00,NaT,Premalatha Maddirala,2023-05-22 15:21:00,Paid,NaT
138,2023-06-12,493051,70655247112,A2I72QKJSAQX9K,A2I72QKJSAQX9KFarah Bhagat,wilko,EU,Technical Onboarding Request - Reintegration,Submitted,2023-05-22 15:20:00,NaT,Farah Bhagat,2023-05-22 15:20:00,Paid,NaT
139,2023-06-12,476544,1206131742,A18FY9ILZV4767,A18FY9ILZV4767KEZIA IDIKKULA MUTHALALY,Alice's Garden France,EU,Technical Onboarding Request - New Seller,WIP,2023-05-03 20:50:00,NaT,KEZIA IDIKKULA MUTHALALY,2023-05-03 20:50:00,Paid,NaT
140,2023-06-12,476514,121075172312,A34GF78PIKBRV5,A34GF78PIKBRV5Himanshu Dhami,Nivian,EU,Technical Onboarding Request - Reintegration,WIP,2023-05-03 19:54:00,NaT,Himanshu Dhami,2023-05-03 19:54:00,Paid,NaT
141,2023-06-12,476322,508544291,ALYY2EOZQ7QUK,ALYY2EOZQ7QUKPRAKASH JHA,MEDIMOPS,EU,Technical Onboarding Request - Reintegration,WIP,2023-05-03 14:39:00,NaT,PRAKASH JHA,2023-05-03 14:39:00,Paid,NaT

In [84]:
astro_combined = pd.concat([astro,astro_paid], ignore_index=True)

astro_combined.to_csv('astro_combined.csv')

In [85]:
# Creating a column "Key" which is a combination of Merchant Token + the Speclalist's name, which would help us compare the feedbacks with cases on Astro
astro_combined['Key'] = astro_combined['Key'].str.upper()
astro_combined['owner'] = astro_combined['owner'].str.upper()
#astro['Key'] = astro.encrypt_id.str.cat(astro.owner)

#Converting the data type of Complete date and start date to Time Format, which is currently is a pandas series format.

# # astro['listing_complete_date'] = pd.to_datetime(astro['listing_complete_date'], format='%Y-%m-%d')
# # astro['create_date'] = pd.to_datetime(astro['create_date'], format='%Y-%m-%d')
astro_combined['merchant_customer_id'].fillna(0)
astro_combined[['run_date','integration_start_date','handoff_date','listing_complete_date','create_date']]= astro[['run_date','integration_start_date','handoff_date','listing_complete_date','create_date']].apply(pd.to_datetime)

astro_combined.head()

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,2023-06-12,1106256,4.789394e+10,A3GQ5ONWIQ9PID,A3GQ5ONWIQ9PIDINDRA TATIKONDA,FindTape (Japan),JP,Technical Onboarding Request - New Seller,Completed,2021-07-21,2021-09-01,INDRA TATIKONDA,2021-08-17,DSR - Migration,2021-08-02
1,2023-06-12,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPREMALATHA MADDIRALA,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,PREMALATHA MADDIRALA,2023-04-20,MIGRATION_AB,2023-04-20
2,2023-06-12,1567266,5.100887e+08,A32URRHD2J995G,A32URRHD2J995GPREMALATHA MADDIRALA,ReinigungsBerater,DE,Push Back,Cancelled,2023-05-04,NaT,PREMALATHA MADDIRALA,NaT,DSR,2023-05-08
3,2023-06-12,1098047,1.471784e+10,A3HOPLRF61I8Z5,A3HOPLRF61I8Z5DILIP CHAVALI,Yuca LTD UK,UK,Technical Onboarding Request - New Seller,Completed,2021-06-08,2021-11-26,DILIP CHAVALI,2021-05-12,3PD_INTEGRATOR,2021-05-12
4,2023-06-12,1573435,4.614223e+07,A2PVIXJF9UTT7R,A2PVIXJF9UTT7RRAJARSHI CHATTERJEE,GourmetGiftBaskets.com,US,Technical Onboarding Request - New Seller,WIP,2023-05-18,NaT,RAJARSHI CHATTERJEE,2023-05-18,migration_1P,2023-05-18

In [86]:
filtered_astro = astro_combined[(astro_combined['listing_complete_date'].dt.year == 2023) | (astro_combined['listing_complete_date'].isnull()) & astro_combined['status'].isin(['Completed', 'WIP', 'Awaiting Information', 'Submitted'])]

In [87]:
# Pivot table to show cases details against each individual

astro_pivot = pd.pivot_table(filtered_astro, index =['owner'], values=['case_number'], columns=['status'], aggfunc= 'count', fill_value = 0)

astro_pivot.to_csv('astro_pivot.csv')

In [88]:

# gives all 2022 cases with all the statuses
#astro_all_22 = astro.loc[(astro['create_date'] >= '2022-01-01')]

#(astro.loc[(astro['listing_complete_date'] >= '2022-01-01') & (astro['listing_complete_date'] < '2022-12-31')]) 

#astro_all_22.to_csv('astro_all_22.csv')

In [89]:
astro_completed= filtered_astro[filtered_astro['status'] =='Completed']

# astro_completed.head(3)

#astro_completed_22 = (astro_completed.loc[(astro_completed['listing_complete_date'].between('2022-01-01','2022-12-31'))])

#astro_completed_22 = (astro_completed.loc[(astro_completed['listing_complete_date'] >= '2022-01-01') & (astro_completed['listing_complete_date'] < '2022-12-31')])

astro_completed.to_csv('astro_completed_23.csv')

astro_completed.head(3) # gives all cases that are completed

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
1,2023-06-12,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPREMALATHA MADDIRALA,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,PREMALATHA MADDIRALA,2023-04-20,MIGRATION_AB,2023-04-20
5,2023-06-12,1345198,1.361387e+10,A39RQLAOUKITT0,A39RQLAOUKITT0KEZIA IDIKKULA MUTHALALY,Marks Electrical Ltd. (Agent of Euronics),UK,Technical Onboarding Request - Reintegration,Completed,2022-08-11,2023-02-01,KEZIA IDIKKULA MUTHALALY,2022-08-18,DSR,2022-08-12
7,2023-06-12,1563737,2.601602e+10,A19KSF3YAVQFA,A19KSF3YAVQFAFARAH BHAGAT,Allianz Assistance,UK,Technical Onboarding Request - New Seller,Completed,2023-04-21,2023-04-21,FARAH BHAGAT,2022-09-09,INSURANCE_FR,2022-09-09

In [90]:
look_up = pd.merge(astro_completed,merged_mod[['Key','SPOC','Average CSAT']], on = 'Key', how= 'left') # Merges and compares feedbacks
# compares owner = spoc, if yes, makes its Feedback 'Yes'. Else: 'No'
look_up.loc[look_up['owner']== look_up['SPOC'], 'Feedback_Received'] = 'Yes'
look_up.loc[look_up['owner']!= look_up['SPOC'], 'Feedback_Received'] = 'No'
look_up['status_notes'] = look_up['status_notes'].str.upper()
look_up = look_up.drop_duplicates(subset=["case_number"], keep='last')
look_up.to_csv('look_up.csv')

In [91]:
cases_due = look_up[look_up.Feedback_Received == 'No']

cases_due.to_csv('cases_due.csv')

In [92]:
tmp_df = look_up[look_up['listing_complete_date'].notnull()]
tmp_df = look_up
tmp_df = tmp_df[['Feedback_Received','owner','Average CSAT']].copy()
pivot_table = tmp_df.pivot_table(
    index=['owner'],
    columns=['Feedback_Received',],
    values=['Feedback_Received',],
    aggfunc={'Feedback_Received': ['count'], 'Average CSAT': ['mean']}
)
pivot_table.columns = ['_'.join([str(c) for c in c_list]) for c_list in pivot_table.columns.values]
look_up_pivot = pivot_table.reset_index()
# Changed Feedback_Received count Yes to dtype int
look_up_pivot['Feedback_Received_count_Yes'] = look_up_pivot['Feedback_Received_count_Yes'].fillna(0).astype('int')
# Changed Feedback_Received count No to dtype int
look_up_pivot['Feedback_Received_count_No'] = look_up_pivot['Feedback_Received_count_No'].fillna(0).astype('int')
# Reordered column Feedback_Received count Yes
look_up_pivot_columns = [col for col in look_up_pivot.columns if col != 'Feedback_Received_count_Yes']
look_up_pivot_columns.insert(1, 'Feedback_Received_count_Yes')
look_up_pivot = look_up_pivot[look_up_pivot_columns]
# Renamed columns APIIS_Specalist
look_up_pivot.rename(columns={'owner': 'APIIS_Specalist'}, inplace=True)
# Renamed columns Feedback_Received (Yes)
look_up_pivot.rename(columns={'Feedback_Received_count_Yes': 'Feedback_Received (Yes)'}, inplace=True)
# Renamed columns Feedback_Received (No)
look_up_pivot.rename(columns={'Feedback_Received_count_No': 'Feedback_Received (No)'}, inplace=True)
# Added column Total Completed Cases
look_up_pivot.insert(3, 'Total Completed Cases', 0)
# Set formula of Total Completed Cases
look_up_pivot['Total Completed Cases'] = look_up_pivot['Feedback_Received (Yes)'] + look_up_pivot['Feedback_Received (No)']
# Added column CSAT Response Rate (%)
look_up_pivot.insert(4, 'CSAT Response Rate (%)', 0)
# Set formula of CSAT Response Rate (%)
look_up_pivot['CSAT Response Rate (%)'] = (look_up_pivot['Feedback_Received (Yes)'] / look_up_pivot['Total Completed Cases']) * 100
# Format the CSAT Response Rate (%) column to have two decimal places
look_up_pivot['CSAT Response Rate (%)'] = look_up_pivot['CSAT Response Rate (%)'].apply(lambda x: '{:.2f}'.format(x))
# Added column average csat
look_up_pivot = look_up_pivot.drop(columns=['Average CSAT_mean_No'])
look_up_pivot['Average CSAT_mean_Yes'] = look_up_pivot['Average CSAT_mean_Yes'].apply(lambda x: '{:.2f}'.format(x))
look_up_pivot = look_up_pivot.rename(columns={'Average CSAT_mean_Yes': 'Average CSAT'})
# Reordered column Feedback Due (No)
look_up_pivot_columns = [col for col in look_up_pivot.columns if col != 'Feedback_Received (No)']
look_up_pivot_columns.insert(2, 'Feedback_Received (No)')
look_up_pivot = look_up_pivot[look_up_pivot_columns]
# Set formula of CSAT Response Rate (%)
look_up_pivot.to_csv('CSAT_RR_Pivot.csv')
look_up_pivot

,APIIS_Specalist,Feedback_Received (Yes),Feedback_Received (No),Total Completed Cases,CSAT Response Rate (%),Average CSAT
0,DILIP CHAVALI,17,11,28,60.71,4.85
1,FARAH BHAGAT,4,11,15,26.67,5.00
2,HARISH GANESAN,4,2,6,66.67,4.50
3,HIMANSHU DHAMI,4,10,14,28.57,4.75
4,INDRA TATIKONDA,3,9,12,25.00,4.33
...,...,...,...,...,...,...
8,NIVEDITHA PARVATHA,9,7,16,56.25,4.67
9,PRAKASH JHA,7,15,22,31.82,5.00
10,PREMALATHA MADDIRALA,8,8,16,50.00,4.75
11,RAJARSHI CHATTERJEE,3,21,24,12.50,5.00
12,YASHWANT KOMATI,2,10,12,16.67,4.75

In [93]:
tmp_df_1 = filtered_astro[['owner', 'status']].copy()
pivot_table = tmp_df_1.pivot_table(
    index=['owner'],
    columns=['status'],
    values=['status'],
    aggfunc={'status': ['count']}
)
pivot_table.columns = [ '_'.join([str(c) for c in c_list]) for c_list in pivot_table.columns.values ]
filtered_astro_pivot = pivot_table.reset_index()
# Changed status count Awaiting Information to dtype int
filtered_astro_pivot['status_count_Awaiting Information'] = filtered_astro_pivot['status_count_Awaiting Information'].fillna(0).astype('int')
# # Changed status count Cancelled to dtype int
filtered_astro_pivot['status_count_Cancelled'] = filtered_astro_pivot['status_count_Cancelled'].fillna(0).astype('int')
# # Changed status count Completed to dtype int
filtered_astro_pivot['status_count_Completed'] = filtered_astro_pivot['status_count_Completed'].fillna(0).astype('int')
# # Changed status count Submitted to dtype int
filtered_astro_pivot['status_count_Submitted'] = filtered_astro_pivot['status_count_Submitted'].fillna(0).astype('int')
# # Changed status count WIP to dtype int
filtered_astro_pivot['status_count_WIP'] = filtered_astro_pivot['status_count_WIP'].fillna(0).astype('int')
# # Renamed columns APIIS_Specalist
filtered_astro_pivot.rename(columns={'owner': 'APIIS_Specalist'}, inplace=True)
# # Renamed columns Awatiting Information
filtered_astro_pivot.rename(columns={'status_count_Awaiting Information': 'Awaiting_Information'}, inplace=True)
# # Renamed columns Cancelled
filtered_astro_pivot.rename(columns={'status_count_Cancelled': 'Cancelled'}, inplace=True)
# # Renamed columns Completed
filtered_astro_pivot.rename(columns={'status_count_Completed': 'Completed'}, inplace=True)
# # Renamed columns Submitted
filtered_astro_pivot.rename(columns={'status_count_Submitted': 'Submitted'}, inplace=True)
# # Renamed columns WIP
filtered_astro_pivot.rename(columns={'status_count_WIP': 'WIP'}, inplace=True)
# # Reordered column Submitted
filtered_astro_pivot_columns = [col for col in filtered_astro_pivot.columns if col != 'Submitted']
filtered_astro_pivot_columns.insert(1, 'Submitted')
filtered_astro_pivot = filtered_astro_pivot[filtered_astro_pivot_columns]
# # Reordered column WIP
filtered_astro_pivot_columns = [col for col in filtered_astro_pivot.columns if col != 'WIP']
filtered_astro_pivot_columns.insert(3, 'WIP')
filtered_astro_pivot = filtered_astro_pivot[filtered_astro_pivot_columns]
filtered_astro_pivot.insert(6, 'Total Cases', 0)
filtered_astro_pivot['Total Cases'] = filtered_astro_pivot['Submitted'] + filtered_astro_pivot['Awaiting_Information']+ filtered_astro_pivot['WIP'] + filtered_astro_pivot['Cancelled'] + filtered_astro_pivot['Completed']
#filtered_astro_pivot[] = sum(filtered_astro_pivot['Submitted'],filtered_astro_pivot['Awaiting_Information'],filtered_astro_pivot['WIP'],filtered_astro_pivot['Cancelled'],filtered_astro_pivot['Completed'])
filtered_astro_pivot
filtered_astro_pivot.to_csv('Case_Level_Metrics_Pivot.csv')

In [94]:
tmp_df_1 = look_up[look_up['listing_complete_date'].notnull()]
tmp_df_1= look_up[look_up['status_notes'].str.contains('PAID' or 'Paid', na=False, regex=False)]
#tmp_df_1 = look_up
tmp_df_1 = tmp_df_1[['Feedback_Received','owner','Average CSAT']].copy()
pivot_table_1 = tmp_df_1.pivot_table(
    index=['owner'],
    columns=['Feedback_Received',],
    values=['Feedback_Received',],
    aggfunc={'Feedback_Received': ['count'], 'Average CSAT': ['mean']}
)
pivot_table_1.columns = ['_'.join([str(c) for c in c_list]) for c_list in pivot_table_1.columns.values]
look_up_pivot_paid = pivot_table_1.reset_index()
# Changed Feedback_Received count Yes to dtype int
look_up_pivot_paid['Feedback_Received_count_Yes'] = look_up_pivot_paid['Feedback_Received_count_Yes'].fillna(0).astype('int')
# Changed Feedback_Received count No to dtype int
look_up_pivot_paid['Feedback_Received_count_No'] = look_up_pivot_paid['Feedback_Received_count_No'].fillna(0).astype('int')
# Reordered column Feedback_Received count Yes
look_up_pivot_paid_columns = [col for col in look_up_pivot_paid.columns if col != 'Feedback_Received_count_Yes']
look_up_pivot_paid_columns.insert(1, 'Feedback_Received_count_Yes')
look_up_pivot_paid = look_up_pivot_paid[look_up_pivot_paid_columns]
# Renamed columns APIIS_Specalist
look_up_pivot_paid.rename(columns={'owner': 'APIIS_Specalist'}, inplace=True)
# Renamed columns Feedback_Received (Yes)
look_up_pivot_paid.rename(columns={'Feedback_Received_count_Yes': 'Feedback_Received (Yes)'}, inplace=True)
# Renamed columns Feedback_Received (No)
look_up_pivot_paid.rename(columns={'Feedback_Received_count_No': 'Feedback_Received (No)'}, inplace=True)
# Added column Total Completed Cases
look_up_pivot_paid.insert(3, 'Total Completed Cases', 0)
# Set formula of Total Completed Cases
look_up_pivot_paid['Total Completed Cases'] = look_up_pivot_paid['Feedback_Received (Yes)'] + look_up_pivot_paid['Feedback_Received (No)']
# Added column CSAT Response Rate (%)
look_up_pivot_paid.insert(4, 'CSAT Response Rate (%)', 0)
# Set formula of CSAT Response Rate (%)
look_up_pivot_paid['CSAT Response Rate (%)'] = (look_up_pivot_paid['Feedback_Received (Yes)'] / look_up_pivot_paid['Total Completed Cases']) * 100
# Format the CSAT Response Rate (%) column to have two decimal places
look_up_pivot_paid['CSAT Response Rate (%)'] = look_up_pivot_paid['CSAT Response Rate (%)'].apply(lambda x: '{:.2f}'.format(x))
# Added column average csat
#look_up_pivot_paid = look_up_pivot_paid.drop(columns=['Average CSAT_mean_No'])
look_up_pivot_paid['Average CSAT_mean_Yes'] = look_up_pivot_paid['Average CSAT_mean_Yes'].apply(lambda x: '{:.2f}'.format(x))
look_up_pivot_paid['Average CSAT_mean_Yes'].fillna('0')
look_up_pivot_paid = look_up_pivot_paid.rename(columns={'Average CSAT_mean_Yes': 'Average CSAT'})
# Reordered column Feedback Due (No)
look_up_pivot_paid_columns = [col for col in look_up_pivot_paid.columns if col != 'Feedback_Received (No)']
look_up_pivot_paid_columns.insert(2, 'Feedback_Received (No)')
look_up_pivot_paid = look_up_pivot_paid[look_up_pivot_paid_columns]
# Set formula of CSAT Response Rate (%)
look_up_pivot_paid.to_csv('CSAT_RR_Paid_Pivot.csv')
look_up_pivot_paid

,APIIS_Specalist,Feedback_Received (Yes),Feedback_Received (No),Average CSAT,Total Completed Cases,CSAT Response Rate (%)
0,DILIP CHAVALI,6,1,5.00,7,85.71
1,FARAH BHAGAT,0,1,nan,1,0.00
2,HARISH GANESAN,1,0,5.00,1,100.00
3,HIMANSHU DHAMI,1,3,5.00,4,25.00
4,INDRA TATIKONDA,2,2,4.50,4,50.00
...,...,...,...,...,...,...
8,NIVEDITHA PARVATHA,3,1,4.33,4,75.00
9,PRAKASH JHA,4,5,5.00,9,44.44
10,PREMALATHA MADDIRALA,2,1,5.00,3,66.67
11,RAJARSHI CHATTERJEE,1,1,5.00,2,50.00
12,YASHWANT KOMATI,1,4,5.00,5,20.00