In [159]:
import requests
import zipfile
import io
import os
import pandas as pd
import datetime
import time

def get_qualtrics_survey_data(dir_save_survey, survey_id):# dir_save_survey is the directory to which these exported files are to be saved.
   
    # Setting user Parameters
    api_token = "nEOlIxeWbcgAkcAbtk9uD8ZyT0YnCQV9AIIRQCcL"
    file_format = "csv"
    data_center = 'amazoneu.syd1' # "<Organization ID>.<Datacenter ID>"
    # Setting static parameters
    request_check_progress = 0
    progress_status = "in progress"
    base_url = "https://{0}.qualtrics.com/API/v3/responseexports/".format(data_center)
    headers = {
        "content-type": "application/json",
        "x-api-token": api_token,
    }
    # Step 1: Creating Data Export
    download_request_url = base_url
    download_request_payload = '{"format":"csv","useLabels": true ,"surveyId":"' + survey_id + '"}' # you can set useLabels:True to get responses in text format
    download_request_response = requests.request("POST", download_request_url, data=download_request_payload, headers=headers)
    progress_id = download_request_response.json()["result"]["id"]
    # print(download_request_response.text)
    # Step 2: Checking on Data Export Progress and waiting until export is ready
    while request_check_progress < 100 and progress_status != "complete":
        request_check_url = base_url + progress_id
        request_check_response = requests.request("GET", request_check_url, headers=headers)
        request_check_progress = request_check_response.json()["result"]["percentComplete"]
    # Step 3: Downloading file
    request_download_url = base_url + progress_id + '/file'
    request_download = requests.request("GET", request_download_url, headers=headers, stream=True)
    # Step 4: Unzipping the file
    zipfile.ZipFile(io.BytesIO(request_download.content)).extractall(dir_save_survey)
    print('Downloaded qualtrics survey')
path = "C:\\Users\\komatiyk\\Downloads\\Qualtrics Weekly Files"

# definining the suvery ID's with Specalist Names
Gurramr = "SV_0Ai7eAuueB6M6gJ"
ddlc = "SV_26alR8n753kAbyu"
dhahiman = "SV_8qdBdGLpsZRHAjA"
Fbhagat = "SV_9mn7lVJCPPAXNTn"
keziaidi = "SV_afMqjeuQ0UOg1qS"
khandh = "SV_8AmcjQKwidXNGG9"
komatiyk = "SV_eRHKjxVDveyIPoG"
mohlipsa = "SV_8w5mrVpJpX5RB6m"
parniv = "SV_6JqeQjoUW0D6RmK"
pratvel = "SV_9nSSDCPpLdaykf4"
Premalatha = "SV_29mXA0vS5qh5HqC"
prkujh= "SV_4HoXXHRb9ptxWbc"
prsrivas= "SV_42bdrRgDB7KUAiW"
rajchat= "SV_7ai49aIbpdjClnw"
tatii = "SV_efHw2haEtbUs7yK"
tgganesa = "SV_5bh19yBpdd1MF3o"
list = [ddlc, dhahiman, Fbhagat, keziaidi, komatiyk, mohlipsa, parniv, pratvel, Premalatha, prkujh, prsrivas, rajchat,tatii,tgganesa]
[get_qualtrics_survey_data(dir_save_survey = path, survey_id = i) for i in list]

Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey
Downloaded qualtrics survey

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [160]:
ddlc = pd.read_csv("Technical Onboarding CSAT- 2022(ddlc).csv")
dhahiman = pd.read_csv("Technical Onboarding CSAT- 2022(dhahiman).csv")
Fbhagat = pd.read_csv("Technical Onboarding CSAT- 2022(Fbhagat).csv")
keziaidi = pd.read_csv("Technical Onboarding CSAT- 2022(keziaidi).csv")
komatiyk = pd.read_csv("Technical Onboarding CSAT- 2022(komatiyk).csv")
mohlipsa = pd.read_csv("Technical Onboarding CSAT- 2022(mohlipsa).csv")
parniv = pd.read_csv("Technical Onboarding CSAT- 2022(parniv).csv")
pratvel = pd.read_csv("Technical Onboarding CSAT- 2022(pratvel).csv")
Premalatha = pd.read_csv("Technical Onboarding CSAT- 2022(Premalatha).csv")
prkujh = pd.read_csv("Technical Onboarding CSAT- 2022(prkujh).csv")
rajchat = pd.read_csv("Technical Onboarding CSAT- 2022(rajchat).csv")
tgganesa = pd.read_csv("Technical Onboarding CSAT- 2022(tgganesa).csv")
tatii = pd.read_csv("Technical Onboarding CSAT- 2022(tatii).csv")

#List1 = (
#     Fbhagat = pd.read_csv("Technical Onboarding CSAT- 2022(Fbhagat).csv"),Premalatha = pd.read_csv("Technical Onboarding CSAT- 2022(Premalatha).csv"),ddlc = pd.read_csv("Technical Onboarding CSAT- 2022(ddlc).csv"),dhahiman = pd.read_csv("Technical Onboarding CSAT- 2022(dhahiman).csv"),keziaidi = pd.read_csv("Technical Onboarding CSAT- 2022(keziaidi).csv"),komatiyk = pd.read_csv("Technical Onboarding CSAT- 2022(komatiyk).csv"),mohlipsa = pd.read_csv("Technical Onboarding CSAT- 2022(mohlipsa).csv"),parniv = pd.read_csv("Technical Onboarding CSAT- 2022(parniv).csv"),pratvel = pd.read_csv("Technical Onboarding CSAT- 2022(pratvel).csv"),prkujh = pd.read_csv("Technical Onboarding CSAT- 2022(prkujh).csv"),
#     rajchat = pd.read_csv("Technical Onboarding CSAT- 2022(rajchat).csv"),tatii = pd.read_csv("Technical Onboarding CSAT- 2022(tatii).csv"),tgganesa = pd.read_csv("Technical Onboarding CSAT- 2022(tgganesa).csv")
# )

In [161]:
# # Names defined as in Astro Report: 'Harish Ganesan', 'Lakshmi Pratyusha Velamakanni', 'Farah Bhagat',
#        'Niveditha Parvatha', 'PRAKASH JHA', 'Premalatha maddirala',
#        'Himanshu Dhami', 'Yashwant Komati', 'Dilip Chavali',
#        'Indra Tatikonda', 'Rajarshi Chatterjee', 'Lipsa Mohanty',
#        'KEZIA IDIKKULA MUTHALALY'

## By doing the below we are adding a column SPOC with the Specalist's name against the feedback received and removing the extra header rows on individual file.

ddlc['SPOC'] = "DILIP CHAVALI"
ddlc.drop([0,1],inplace= True)
Fbhagat['SPOC'] = "FARAH BHAGAT"
Fbhagat.drop([0,1],inplace= True)
dhahiman['SPOC'] = "HIMANSHU DHAMI"
dhahiman.drop([0,1],inplace= True)
keziaidi['SPOC'] = "KEZIA IDIKKULA MUTHALALY"
keziaidi.drop([0,1],inplace= True)
komatiyk['SPOC'] = "YASHWANT KOMATI"
komatiyk.drop([0,1],inplace= True)
mohlipsa['SPOC'] = "LIPSA MOHANTY"
mohlipsa.drop([0,1],inplace= True)
parniv['SPOC'] = "NIVEDITHA PARVATHA"
parniv.drop([0,1],inplace= True)
pratvel['SPOC'] = "LAKSHMI PRATYUSHA VELAMAKANNI"
pratvel.drop([0,1],inplace= True)
Premalatha['SPOC'] = "PREMALATHA MADDIRALA"
Premalatha.drop([0,1],inplace= True)
prkujh['SPOC'] = "PRAKASH JHA"
prkujh.drop([0,1],inplace= True)
rajchat['SPOC'] = "RAJARSHI CHATTERJEE"
rajchat.drop([0,1],inplace= True)
tgganesa['SPOC'] = "HARISH GANESAN"
tgganesa.drop([0,1],inplace= True)
tatii['SPOC'] = "INDRA TATIKONDA"
tatii.drop([0,1],inplace= True)

In [162]:
df_merged = pd.concat([ddlc,dhahiman, Fbhagat, keziaidi, komatiyk, mohlipsa, parniv, pratvel, Premalatha, prkujh, rajchat, tgganesa, tatii])

df_merged # All Feedbacks

,ResponseID,ResponseSet,IPAddress,StartDate,EndDate,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,...,Q2_1,Q3,Q4,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC,Score-sum,Score-weightedAvg,Score-weightedStdDev
2,R_3maDsWCzZBHBNUu,NaN,91.241.18.19,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,...,3 -Fair,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI,NaN,NaN,NaN
3,R_C36gknwR1sf3SPD,NaN,3.88.93.236,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,...,5- Excellent,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI,NaN,NaN,NaN
4,R_2YldibFOkrIilqh,NaN,52.95.75.9,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,...,5- Excellent,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI,NaN,NaN,NaN
5,R_3jd1JKYRO0XKwUF,NaN,93.56.31.152,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,...,5- Excellent,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI,NaN,NaN,NaN
6,R_1EhQUTTXRKWcd2S,NaN,87.200.21.74,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,...,4- Good,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,R_aXmONjsqo2ngM8x,NaN,213.233.57.205,2023-02-09 17:51:24,2023-02-09 17:55:04,NaN,NaN,NaN,NaN,1,...,5- Excellent,A3BO896EZRBKN6,useful and kind,41.8904,12.5126,-1,INDRA TATIKONDA,NaN,NaN,NaN
43,R_2VK4d53HhpL68xJ,NaN,2.81.182.225,2023-04-17 23:54:37,2023-04-17 23:55:27,NaN,NaN,NaN,NaN,1,...,4- Good,A3ATQKDA5FUQPW,.,39.0349,-9.3754,-1,INDRA TATIKONDA,NaN,NaN,NaN
44,R_1C1NZH1WRa7bGu2,NaN,87.120.199.15,2023-04-19 07:54:43,2023-04-19 07:55:26,NaN,NaN,NaN,NaN,1,...,5- Excellent,A19ULV6V7NBUWD,"Great, responsive and professional support",42.696,23.332,-1,INDRA TATIKONDA,NaN,NaN,NaN
45,R_1DIr2SUuQmDmDSZ,NaN,78.134.72.11,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,...,5- Excellent,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA,NaN,NaN,NaN
46,R_1jdgmhL8zo6tYpL,NaN,51.155.23.77,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,...,5- Excellent,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA,NaN,NaN,NaN

In [163]:
#Dropping unneccesary columns and renaming certain columns for easy reference.

merged_mod = df_merged.drop(columns=['ResponseID','ResponseSet','IPAddress','Score-sum','Score-weightedAvg','Score-weightedStdDev'])

merged_mod.rename(columns={'StartDate': 'Start_Date', 'EndDate': 'End_date','RecipientLastName': 'Specalist_Name', 'Q1': 'Rating of the overall Support','Q2_1': 'Knowledge of SP-API products & Services','Q2_2': 'Ability to communicate clearly','Q3': 'Merchant_Token', 'Q4': 'Comments'}, inplace=True)

merged_mod[['Start_Date','End_date']]= merged_mod[['Start_Date','End_date']].apply(pd.to_datetime)

merged_mod['Merchant_Token'].fillna('0')

merged_mod

,Start_Date,End_date,Specalist_Name,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,Status,Rating of the overall Support,Ability to communicate clearly,Knowledge of SP-API products & Services,Merchant_Token,Comments,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC
2,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,3 -Fair,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI
3,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI
4,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI
5,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,5- Excellent,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI
6,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,0,4- Good,5- Excellent,4- Good,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-02-09 17:51:24,2023-02-09 17:55:04,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A3BO896EZRBKN6,useful and kind,41.8904,12.5126,-1,INDRA TATIKONDA
43,2023-04-17 23:54:37,2023-04-17 23:55:27,NaN,NaN,NaN,NaN,1,0,4- Good,4- Good,4- Good,A3ATQKDA5FUQPW,.,39.0349,-9.3754,-1,INDRA TATIKONDA
44,2023-04-19 07:54:43,2023-04-19 07:55:26,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A19ULV6V7NBUWD,"Great, responsive and professional support",42.696,23.332,-1,INDRA TATIKONDA
45,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA
46,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5- Excellent,5- Excellent,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA

In [164]:
# Creating a column "Key" which is a combination of Merchant Token + the Speclalist's name, which would help us compare the feedbacks with cases on Astro

merged_mod['Key'] = merged_mod.Merchant_Token.str.cat(merged_mod.SPOC)

merged_mod['Ability to communicate clearly'] = merged_mod['Ability to communicate clearly'].astype(str).str.split('-').str[0].astype(int)
merged_mod['Knowledge of SP-API products & Services'] = merged_mod['Knowledge of SP-API products & Services'].astype(str).str.split('-').str[0].astype(int)

merged_mod['Average CSAT'] = (merged_mod['Ability to communicate clearly'] + merged_mod['Knowledge of SP-API products & Services']) / 2

merged_mod

,Start_Date,End_date,Specalist_Name,RecipientFirstName,RecipientEmail,ExternalDataReference,Finished,Status,Rating of the overall Support,Ability to communicate clearly,Knowledge of SP-API products & Services,Merchant_Token,Comments,LocationLatitude,LocationLongitude,LocationAccuracy,SPOC,Key,Average CSAT
2,2021-10-11 10:02:35,2021-10-11 10:05:58,NaN,NaN,NaN,NaN,1,0,4- Good,5,3,A11OKMLEOWRUTY,NaN,59.89830017089844,30.261795043945312,-1,DILIP CHAVALI,A11OKMLEOWRUTYDILIP CHAVALI,4.0
3,2021-11-18 14:08:39,2021-11-18 14:12:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A1Y1NMNJFO9AZH,NaN,39.046905517578125,-77.49030303955078,-1,DILIP CHAVALI,A1Y1NMNJFO9AZHDILIP CHAVALI,5.0
4,2021-11-24 11:46:50,2021-11-24 11:56:01,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A2WJJHFR3EZX13,Dilip has been very helpful and approachable throughout the process. It was great working with him :),19.074798583984375,72.88560485839844,-1,DILIP CHAVALI,A2WJJHFR3EZX13DILIP CHAVALI,5.0
5,2021-11-24 17:05:45,2021-11-24 17:09:03,NaN,NaN,NaN,NaN,1,0,4- Good,5,5,A39JLZTLGJEAS9,NaN,41.89039611816406,12.512603759765625,-1,DILIP CHAVALI,A39JLZTLGJEAS9DILIP CHAVALI,5.0
6,2021-11-25 08:19:20,2021-11-25 08:21:01,NaN,NaN,NaN,NaN,1,0,4- Good,5,4,lenish@dynamicsstream.com,"Still, our project work is going on. We should be able to complete our work by 15th Dec with all your support.",25.2633056640625,55.30870056152344,-1,DILIP CHAVALI,lenish@dynamicsstream.comDILIP CHAVALI,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-02-09 17:51:24,2023-02-09 17:55:04,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A3BO896EZRBKN6,useful and kind,41.8904,12.5126,-1,INDRA TATIKONDA,A3BO896EZRBKN6INDRA TATIKONDA,5.0
43,2023-04-17 23:54:37,2023-04-17 23:55:27,NaN,NaN,NaN,NaN,1,0,4- Good,4,4,A3ATQKDA5FUQPW,.,39.0349,-9.3754,-1,INDRA TATIKONDA,A3ATQKDA5FUQPWINDRA TATIKONDA,4.0
44,2023-04-19 07:54:43,2023-04-19 07:55:26,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A19ULV6V7NBUWD,"Great, responsive and professional support",42.696,23.332,-1,INDRA TATIKONDA,A19ULV6V7NBUWDINDRA TATIKONDA,5.0
45,2023-05-02 11:43:36,2023-05-02 11:44:51,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A29BCDAL77UPK2,NaN,45.7333,8.5626,-1,INDRA TATIKONDA,A29BCDAL77UPK2INDRA TATIKONDA,5.0
46,2023-05-16 11:56:15,2023-05-16 12:16:19,NaN,NaN,NaN,NaN,1,0,5- Excellent,5,5,A1023IQIDP1IRB,Absolutely fantastic support. Indra was very patient with me and talked me through every stage. Amazon should be proud of having Indra work for them. Thank you,51.6445,-3.9775,-1,INDRA TATIKONDA,A1023IQIDP1IRBINDRA TATIKONDA,5.0

In [166]:
merged_mod.to_csv('Merged_FB_File.csv') # Converting the aggregated feedbacks to a CSV file

In [266]:
astro = pd.read_csv('DataAstro.csv') # Importing astro report without paid
astro = astro.rename(columns={'key': 'Key'})
astro[['create_date','listing_complete_date', 'integration_start_date','handoff_date']]= astro[['create_date','listing_complete_date', 'integration_start_date','handoff_date']].apply(pd.to_datetime)
astro

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,6/12/2023,1567266,5.100887e+08,A32URRHD2J995G,A32URRHD2J995GPremalatha Maddirala,ReinigungsBerater,DE,Push Back,Cancelled,2023-05-04,NaT,Premalatha Maddirala,NaT,DSR,2023-05-08
1,6/12/2023,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPremalatha Maddirala,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,Premalatha Maddirala,2023-04-20,MIGRATION_AB,2023-04-20
2,6/12/2023,1322518,2.870000e+11,ABLP6WLSTB1T7,ABLP6WLSTB1T7Yashwant Komati,Carusando srl,IT,Technical Onboarding Request - New Seller,Cancelled,2022-05-23,2022-11-07,Yashwant Komati,2022-06-09,DSR,2022-05-24
3,6/12/2023,1313919,1.248097e+09,AYRHL1BC4CIOF,AYRHL1BC4CIOFDilip Chavali,sportstech,DE,Technical Onboarding Request - New Seller,WIP,2022-04-25,NaT,Dilip Chavali,2022-05-20,SMART_CONNECT_EU,2022-04-25
4,6/12/2023,1093493,1.940000e+11,AVSKIMAGSPF6S,AVSKIMAGSPF6SIndra Tatikonda,Yves Rocher Nordic,SE,Technical Onboarding Request - New Seller,Cancelled,2021-05-15,NaT,Indra Tatikonda,2021-05-19,NaN,2021-05-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,6/12/2023,1323665,2.640000e+11,A3QO5UC2203QP9,A3QO5UC2203QP9Yashwant Komati,Christopher Kane EU,UK,Technical Onboarding Request - New Seller,Completed,2022-05-26,2022-06-15,Yashwant Komati,2022-05-27,BRAND_OWNER--MCID: A45WGWJYWNE5C,2022-05-27
1199,6/12/2023,1342115,2.960000e+11,A255VJ51WOUTZK,A255VJ51WOUTZKIndra Tatikonda,LuLu,AE,Technical Onboarding Request - New Seller,Completed,2022-08-01,2022-12-09,Indra Tatikonda,2022-08-01,F3_AE,2022-05-01
1200,6/12/2023,1134448,5.905828e+08,AOEAIE3TQ08UN,AOEAIE3TQ08UNYashwant Komati,ߥǇame___OutletߥǠPreise inkl. MwSt.,DE,Technical Onboarding Request - Reintegration,Completed,2021-12-14,2021-11-24,Yashwant Komati,2021-08-02,PAID_SERVICES,2021-08-02
1201,6/12/2023,1337446,2.390000e+11,A3VPICPCTEPXIW,A3VPICPCTEPXIWFarah Bhagat,Smart Brands Laboratory AE,AE,Technical Onboarding Request - New Seller,Cancelled,2022-07-14,NaT,Farah Bhagat,2022-07-25,AE-DSR_INTEGRATOR,2022-07-15
1202,6/12/2023,1396366,3.070000e+11,AF5HXFYWU2PWF,AF5HXFYWU2PWFIndra Tatikonda,Naf Naf España,ES,Technical Onboarding Request - New Seller,Cancelled,2023-01-23,NaT,Indra Tatikonda,NaT,DSR,2023-01-25

In [267]:
astro_paid = pd.read_excel('Astro_Paid.xlsx', sheet_name='Paid')
astro_paid = astro_paid.rename(columns={'key': 'Key'})
astro_paid[['create_date','listing_complete_date', 'integration_start_date','handoff_date']]= astro_paid[['create_date','listing_complete_date', 'integration_start_date','handoff_date']].apply(pd.to_datetime)
astro_paid

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,2023-06-12,163175,1211291772,AUNGYH863E97M,AUNGYH863E97MDilip Chavali,vidaXL IT,EU,Technical Onboarding Request - New Seller,Completed,2022-05-11 00:00:00,2023-04-24 16:22:00,Dilip Chavali,2022-05-11 20:51:00,PAID,NaT
1,2023-06-12,182768,47590974012,A3Q145GG5GOJFD,A3Q145GG5GOJFDNiveditha Parvatha,Joyería TOUS,EU,Technical Onboarding Request - New Seller,Completed,2022-06-14 00:00:00,2023-03-10 00:00:00,Niveditha Parvatha,2022-06-14 02:34:00,PAID,NaT
2,2023-06-12,220004,757310623,A175O6N7UW1356,A175O6N7UW1356PRAKASH JHA,S&O Handelsgesellschaft mbH,EU,Technical Onboarding Request - Reintegration,WIP,2022-08-08 00:00:00,NaT,PRAKASH JHA,2022-08-08 15:45:00,Paid,NaT
3,2023-06-12,247216,7647118235,A27DL0OMONAIX2,A27DL0OMONAIX2Yashwant Komati,Juvenilis,EU,Technical Onboarding Request - Reintegration,Completed,2022-09-13 20:48:00,2023-04-24 16:33:00,Yashwant Komati,2022-09-13 20:48:00,PAID,NaT
4,2023-06-12,261671,14816121112,A3I7IG61W9TCJR,A3I7IG61W9TCJRLipsa Mohanty,LULUBUY S.A.R.L,EU,Technical Onboarding Request - Reintegration,Completed,2022-09-29 21:44:00,2023-04-12 01:13:00,Lipsa Mohanty,2022-09-29 21:44:00,PAID,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,2023-06-12,493052,78178837412,A16KNVL00HJUQF,A16KNVL00HJUQFPremalatha Maddirala,Tudetic,EU,Technical Onboarding Request - New Seller,WIP,2023-05-22 15:21:00,NaT,Premalatha Maddirala,2023-05-22 15:21:00,Paid,NaT
138,2023-06-12,493051,70655247112,A2I72QKJSAQX9K,A2I72QKJSAQX9KFarah Bhagat,wilko,EU,Technical Onboarding Request - Reintegration,Submitted,2023-05-22 15:20:00,NaT,Farah Bhagat,2023-05-22 15:20:00,Paid,NaT
139,2023-06-12,476544,1206131742,A18FY9ILZV4767,A18FY9ILZV4767KEZIA IDIKKULA MUTHALALY,Alice's Garden France,EU,Technical Onboarding Request - New Seller,WIP,2023-05-03 20:50:00,NaT,KEZIA IDIKKULA MUTHALALY,2023-05-03 20:50:00,Paid,NaT
140,2023-06-12,476514,121075172312,A34GF78PIKBRV5,A34GF78PIKBRV5Himanshu Dhami,Nivian,EU,Technical Onboarding Request - Reintegration,WIP,2023-05-03 19:54:00,NaT,Himanshu Dhami,2023-05-03 19:54:00,Paid,NaT
141,2023-06-12,476322,508544291,ALYY2EOZQ7QUK,ALYY2EOZQ7QUKPRAKASH JHA,MEDIMOPS,EU,Technical Onboarding Request - Reintegration,WIP,2023-05-03 14:39:00,NaT,PRAKASH JHA,2023-05-03 14:39:00,Paid,NaT

In [268]:
astro_combined = pd.concat([astro,astro_paid], ignore_index=True)

astro_combined.to_csv('astro_combined.csv')

In [269]:
# Creating a column "Key" which is a combination of Merchant Token + the Speclalist's name, which would help us compare the feedbacks with cases on Astro
astro_combined['Key'] = astro_combined['Key'].str.upper()
astro_combined['owner'] = astro_combined['owner'].str.upper()
#astro['Key'] = astro.encrypt_id.str.cat(astro.owner)

#Converting the data type of Complete date and start date to Time Format, which is currently is a pandas series format.

# # astro['listing_complete_date'] = pd.to_datetime(astro['listing_complete_date'], format='%Y-%m-%d')
# # astro['create_date'] = pd.to_datetime(astro['create_date'], format='%Y-%m-%d')
astro_combined['merchant_customer_id'].fillna(0)
astro_combined[['run_date','integration_start_date','handoff_date','listing_complete_date','create_date']]= astro[['run_date','integration_start_date','handoff_date','listing_complete_date','create_date']].apply(pd.to_datetime)

astro_combined.head()

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
0,2023-06-12,1567266,5.100887e+08,A32URRHD2J995G,A32URRHD2J995GPREMALATHA MADDIRALA,ReinigungsBerater,DE,Push Back,Cancelled,2023-05-04,NaT,PREMALATHA MADDIRALA,NaT,DSR,2023-05-08
1,2023-06-12,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPREMALATHA MADDIRALA,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,PREMALATHA MADDIRALA,2023-04-20,MIGRATION_AB,2023-04-20
2,2023-06-12,1322518,2.870000e+11,ABLP6WLSTB1T7,ABLP6WLSTB1T7YASHWANT KOMATI,Carusando srl,IT,Technical Onboarding Request - New Seller,Cancelled,2022-05-23,2022-11-07,YASHWANT KOMATI,2022-06-09,DSR,2022-05-24
3,2023-06-12,1313919,1.248097e+09,AYRHL1BC4CIOF,AYRHL1BC4CIOFDILIP CHAVALI,sportstech,DE,Technical Onboarding Request - New Seller,WIP,2022-04-25,NaT,DILIP CHAVALI,2022-05-20,SMART_CONNECT_EU,2022-04-25
4,2023-06-12,1093493,1.940000e+11,AVSKIMAGSPF6S,AVSKIMAGSPF6SINDRA TATIKONDA,Yves Rocher Nordic,SE,Technical Onboarding Request - New Seller,Cancelled,2021-05-15,NaT,INDRA TATIKONDA,2021-05-19,NaN,2021-05-18

In [270]:
filtered_astro = astro_combined[(astro_combined['listing_complete_date'].dt.year == 2023) | (astro_combined['listing_complete_date'].isnull()) & astro_combined['status'].isin(['Completed', 'WIP', 'Awaiting Information', 'Submitted'])]

In [271]:
# Pivot table to show cases details against each individual

astro_pivot = pd.pivot_table(filtered_astro, index =['owner'], values=['case_number'], columns=['status'], aggfunc= 'count', fill_value = 0)

astro_pivot.to_csv('astro_pivot.csv')

In [272]:

# gives all 2022 cases with all the statuses
#astro_all_22 = astro.loc[(astro['create_date'] >= '2022-01-01')]

#(astro.loc[(astro['listing_complete_date'] >= '2022-01-01') & (astro['listing_complete_date'] < '2022-12-31')]) 

#astro_all_22.to_csv('astro_all_22.csv')

In [285]:
astro_completed= filtered_astro[filtered_astro['status'] =='Completed']

# astro_completed.head(3)

#astro_completed_22 = (astro_completed.loc[(astro_completed['listing_complete_date'].between('2022-01-01','2022-12-31'))])

#astro_completed_22 = (astro_completed.loc[(astro_completed['listing_complete_date'] >= '2022-01-01') & (astro_completed['listing_complete_date'] < '2022-12-31')])

astro_completed.to_csv('astro_completed_23.csv')

astro_completed.head(3) # gives all cases that are completed

,run_date,case_number,merchant_customer_id,encrypted_id,Key,account_name,astro_mkp,type_of_request,status,create_date,listing_complete_date,owner,integration_start_date,status_notes,handoff_date
1,2023-06-12,1563542,2.867124e+10,AB36Q4XFJK40H,AB36Q4XFJK40HPREMALATHA MADDIRALA,Wifi Stock UK,UK,Technical Onboarding Request - New Seller,Completed,2023-04-20,2023-06-01,PREMALATHA MADDIRALA,2023-04-20,MIGRATION_AB,2023-04-20
12,2023-06-12,1528788,6.674952e+10,A5A5GZ6GOPBBW,A5A5GZ6GOPBBWPREMALATHA MADDIRALA,Década Studio,UK,Technical Onboarding Request - New Seller,Completed,2023-03-07,2023-05-16,PREMALATHA MADDIRALA,2023-03-17,AGENCY_ES,2023-03-07
16,2023-06-12,1563737,2.601602e+10,A19KSF3YAVQFA,A19KSF3YAVQFAFARAH BHAGAT,Allianz Assistance,UK,Technical Onboarding Request - New Seller,Completed,2023-04-21,2023-04-21,FARAH BHAGAT,2022-09-09,INSURANCE_FR,2022-09-09

In [287]:
look_up = pd.merge(astro_completed,merged_mod[['Key','SPOC','Average CSAT']], on = 'Key', how= 'left') # Merges and compares feedbacks
# compares owner = spoc, if yes, makes its Feedback 'Yes'. Else: 'No'
look_up.loc[look_up['owner']== look_up['SPOC'], 'Feedback_Received'] = 'Yes'
look_up.loc[look_up['owner']!= look_up['SPOC'], 'Feedback_Received'] = 'No'
look_up = look_up.drop_duplicates(subset=["case_number"], keep='last')
look_up.to_csv('look_up.csv')

In [ ]:
cases_due = look_up[look_up.Feedback_Received == 'No']

cases_due.to_csv('cases_due.csv')

In [292]:
#tmp_df = look_up[look_up['listing_complete_date'].notnull()]
tmp_df = look_up
tmp_df = tmp_df[['Feedback_Received','owner','Average CSAT']].copy()
pivot_table = tmp_df.pivot_table(
    index=['owner'],
    columns=['Feedback_Received',],
    values=['Feedback_Received',],
    aggfunc={'Feedback_Received': ['count'], 'Average CSAT': ['mean']}
)
pivot_table.columns = ['_'.join([str(c) for c in c_list]) for c_list in pivot_table.columns.values]
look_up_pivot = pivot_table.reset_index()
# Changed Feedback_Received count Yes to dtype int
look_up_pivot['Feedback_Received_count_Yes'] = look_up_pivot['Feedback_Received_count_Yes'].fillna(0).astype('int')
# Changed Feedback_Received count No to dtype int
look_up_pivot['Feedback_Received_count_No'] = look_up_pivot['Feedback_Received_count_No'].fillna(0).astype('int')
# Reordered column Feedback_Received count Yes
look_up_pivot_columns = [col for col in look_up_pivot.columns if col != 'Feedback_Received_count_Yes']
look_up_pivot_columns.insert(1, 'Feedback_Received_count_Yes')
look_up_pivot = look_up_pivot[look_up_pivot_columns]
# Renamed columns APIIS_Specalist
look_up_pivot.rename(columns={'owner': 'APIIS_Specalist'}, inplace=True)
# Renamed columns Feedback_Received (Yes)
look_up_pivot.rename(columns={'Feedback_Received_count_Yes': 'Feedback_Received (Yes)'}, inplace=True)
# Renamed columns Feedback_Received (No)
look_up_pivot.rename(columns={'Feedback_Received_count_No': 'Feedback_Received (No)'}, inplace=True)
# Added column Total Completed Cases
look_up_pivot.insert(3, 'Total Completed Cases', 0)
# Set formula of Total Completed Cases
look_up_pivot['Total Completed Cases'] = look_up_pivot['Feedback_Received (Yes)'] + look_up_pivot['Feedback_Received (No)']
# Added column CSAT Response Rate (%)
look_up_pivot.insert(4, 'CSAT Response Rate (%)', 0)
# Set formula of CSAT Response Rate (%)
look_up_pivot['CSAT Response Rate (%)'] = (look_up_pivot['Feedback_Received (Yes)'] / look_up_pivot['Total Completed Cases']) * 100
# Format the CSAT Response Rate (%) column to have two decimal places
look_up_pivot['CSAT Response Rate (%)'] = look_up_pivot['CSAT Response Rate (%)'].apply(lambda x: '{:.2f}'.format(x))
# Added column average csat
look_up_pivot = look_up_pivot.drop(columns=['Average CSAT_mean_No'])
look_up_pivot['Average CSAT_mean_Yes'] = look_up_pivot['Average CSAT_mean_Yes'].apply(lambda x: '{:.2f}'.format(x))
look_up_pivot = look_up_pivot.rename(columns={'Average CSAT_mean_Yes': 'Average CSAT'})
# Set formula of CSAT Response Rate (%)
look_up_pivot.to_csv('CSAT_RR_Pivot.csv')
look_up_pivot

,APIIS_Specalist,Feedback_Received (Yes),Total Completed Cases,CSAT Response Rate (%),Average CSAT,Feedback_Received (No)
0,DILIP CHAVALI,16,26,61.54,4.84,10
1,FARAH BHAGAT,4,14,28.57,5.00,10
2,HARISH GANESAN,4,6,66.67,4.50,2
3,HIMANSHU DHAMI,4,14,28.57,4.75,10
4,INDRA TATIKONDA,3,12,25.00,4.33,9
...,...,...,...,...,...,...
8,NIVEDITHA PARVATHA,9,16,56.25,4.67,7
9,PRAKASH JHA,7,22,31.82,5.00,15
10,PREMALATHA MADDIRALA,8,16,50.00,4.75,8
11,RAJARSHI CHATTERJEE,3,19,15.79,5.00,16
12,YASHWANT KOMATI,2,9,22.22,4.75,7

In [293]:
tmp_df_1 = filtered_astro[['owner', 'status']].copy()
pivot_table = tmp_df_1.pivot_table(
    index=['owner'],
    columns=['status'],
    values=['status'],
    aggfunc={'status': ['count']}
)
pivot_table.columns = [ '_'.join([str(c) for c in c_list]) for c_list in pivot_table.columns.values ]
filtered_astro_pivot = pivot_table.reset_index()
# Changed status count Awaiting Information to dtype int
filtered_astro_pivot['status_count_Awaiting Information'] = filtered_astro_pivot['status_count_Awaiting Information'].fillna(0).astype('int')
# # Changed status count Cancelled to dtype int
filtered_astro_pivot['status_count_Cancelled'] = filtered_astro_pivot['status_count_Cancelled'].fillna(0).astype('int')
# # Changed status count Completed to dtype int
filtered_astro_pivot['status_count_Completed'] = filtered_astro_pivot['status_count_Completed'].fillna(0).astype('int')
# # Changed status count Submitted to dtype int
filtered_astro_pivot['status_count_Submitted'] = filtered_astro_pivot['status_count_Submitted'].fillna(0).astype('int')
# # Changed status count WIP to dtype int
filtered_astro_pivot['status_count_WIP'] = filtered_astro_pivot['status_count_WIP'].fillna(0).astype('int')
# # Renamed columns APIIS_Specalist
filtered_astro_pivot.rename(columns={'owner': 'APIIS_Specalist'}, inplace=True)
# # Renamed columns Awatiting Information
filtered_astro_pivot.rename(columns={'status_count_Awaiting Information': 'Awaiting_Information'}, inplace=True)
# # Renamed columns Cancelled
filtered_astro_pivot.rename(columns={'status_count_Cancelled': 'Cancelled'}, inplace=True)
# # Renamed columns Completed
filtered_astro_pivot.rename(columns={'status_count_Completed': 'Completed'}, inplace=True)
# # Renamed columns Submitted
filtered_astro_pivot.rename(columns={'status_count_Submitted': 'Submitted'}, inplace=True)
# # Renamed columns WIP
filtered_astro_pivot.rename(columns={'status_count_WIP': 'WIP'}, inplace=True)
# # Reordered column Submitted
filtered_astro_pivot_columns = [col for col in filtered_astro_pivot.columns if col != 'Submitted']
filtered_astro_pivot_columns.insert(1, 'Submitted')
filtered_astro_pivot = filtered_astro_pivot[filtered_astro_pivot_columns]
# # Reordered column WIP
filtered_astro_pivot_columns = [col for col in filtered_astro_pivot.columns if col != 'WIP']
filtered_astro_pivot_columns.insert(3, 'WIP')
filtered_astro_pivot = filtered_astro_pivot[filtered_astro_pivot_columns]
filtered_astro_pivot.insert(6, 'Total Cases', 0)
filtered_astro_pivot['Total Cases'] = filtered_astro_pivot['Submitted'] + filtered_astro_pivot['Awaiting_Information']+ filtered_astro_pivot['WIP'] + filtered_astro_pivot['Cancelled'] + filtered_astro_pivot['Completed']
#filtered_astro_pivot[] = sum(filtered_astro_pivot['Submitted'],filtered_astro_pivot['Awaiting_Information'],filtered_astro_pivot['WIP'],filtered_astro_pivot['Cancelled'],filtered_astro_pivot['Completed'])
filtered_astro_pivot
#filtered_astro_pivot.to_csv('Case_Level_Metrics_Pivot.csv')

,APIIS_Specalist,Submitted,Awaiting_Information,WIP,Cancelled,Completed,Total Cases
0,DILIP CHAVALI,5,1,26,0,26,58
1,FARAH BHAGAT,3,3,38,0,14,58
2,HARISH GANESAN,1,0,0,0,6,7
3,HIMANSHU DHAMI,7,0,24,0,14,45
4,INDRA TATIKONDA,11,2,9,0,12,34
...,...,...,...,...,...,...,...
8,NIVEDITHA PARVATHA,11,2,16,0,16,45
9,PRAKASH JHA,2,0,27,1,22,52
10,PREMALATHA MADDIRALA,3,2,22,0,16,43
11,RAJARSHI CHATTERJEE,0,0,30,0,19,49
12,YASHWANT KOMATI,8,5,8,0,9,30